function [psi_a, psi_b] = Real_time_evolve_sphere( ...
    psi_a, psi_b, ...
    m_a, m_b, ...
    g_a, g_b, g_ab, ...
    N_a, N_b, ...
    L_z, ...
    Mat_V_a, Mat_V_b, ...
    geom, hbar, dt)

%REAL_TIME_EVOLVE_SPHERE
% One RK4 step of the coupled real-time GPEs on a sphere,
% followed by renormalization of both components.

    [Hpsi_a, Hpsi_b] = Real_time_iteration_sphere( ...
        psi_a, psi_b, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);

    k_1_a = -1i * dt / hbar * Hpsi_a;
    k_1_b = -1i * dt / hbar * Hpsi_b;

    [Hpsi_a, Hpsi_b] = Real_time_iteration_sphere( ...
        psi_a + k_1_a/2, psi_b + k_1_b/2, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);

    k_2_a = -1i * dt / hbar * Hpsi_a;
    k_2_b = -1i * dt / hbar * Hpsi_b;

    [Hpsi_a, Hpsi_b] = Real_time_iteration_sphere( ...
        psi_a + k_2_a/2, psi_b + k_2_b/2, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);

    k_3_a = -1i * dt / hbar * Hpsi_a;
    k_3_b = -1i * dt / hbar * Hpsi_b;

    [Hpsi_a, Hpsi_b] = Real_time_iteration_sphere( ...
        psi_a + k_3_a, psi_b + k_3_b, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);

    k_4_a = -1i * dt / hbar * Hpsi_a;
    k_4_b = -1i * dt / hbar * Hpsi_b;

    psi_a = psi_a + (k_1_a + 2*k_2_a + 2*k_3_a + k_4_a)/6;
    psi_b = psi_b + (k_1_b + 2*k_2_b + 2*k_3_b + k_4_b)/6;

    % Optional weak spectral filtering if needed
    psi_a = Spectral_filter_sphere(psi_a, geom, 18);
    psi_b = Spectral_filter_sphere(psi_b, geom, 18);

    % Renormalize both components
    psi_a = sphere_normalize(psi_a, geom.W);
    psi_b = sphere_normalize(psi_b, geom.W);

end