function Check_ssht_dependency
%CHECK_SSHT_DEPENDENCY Verify that the required SSHT functions are available.
%
%   Raises an informative error when the SSHT MATLAB library is not on the
%   MATLAB path.

required_functions = { ...
    'ssht_sampling', ...
    'ssht_forward', ...
    'ssht_inverse', ...
    'ssht_plot_sphere'};

missing = required_functions(cellfun(@(name) exist(name, 'file') == 0, ...
    required_functions));

if ~isempty(missing)
    error('massiveVortexDipole:MissingSSHT', ...
        ['Required SSHT function(s) not found: %s. Install the SSHT MATLAB ' ...
         'library and add it to the MATLAB path.'], strjoin(missing, ', '));
end
end
