function [psi_a, psi_b, Hpsi_a, Hpsi_b] = Imaginary_time_evolve_sphere( ...
    psi_a, psi_b, ...
    m_a, m_b, ...
    g_a, g_b, g_ab, ...
    N_a, N_b, ...
    L_z, ...
    Mat_V_a, Mat_V_b, ...
    geom, hbar, dt)

%IMAGINARY_TIME_EVOLVE_SPHERE Perform one normalized imaginary-time step.
%
%   Advances both condensate components by one first-order imaginary-time
%   step, applies the spectral filter, normalizes each component on the
%   sphere, and recomputes the Hamiltonian action on the updated state.
%
%   Wavefunctions are normalized to unity; atom numbers enter explicitly
%   in the nonlinear terms. Energies and couplings are expressed in SI units.

    [Hpsi_a, Hpsi_b] = Imaginary_time_iteration_sphere( ...
        psi_a, psi_b, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);

    k_1_a = -dt/hbar * Hpsi_a;
    k_1_b = -dt/hbar * Hpsi_b;

    psi_a = psi_a + k_1_a;
    psi_b = psi_b + k_1_b;

    psi_a = Spectral_filter_sphere(psi_a, geom, 18);
    psi_b = Spectral_filter_sphere(psi_b, geom, 18);

    psi_a = sphere_normalize(psi_a, geom.W);
    psi_b = sphere_normalize(psi_b, geom.W);

    % Recompute Hpsi on the updated normalized states
    [Hpsi_a, Hpsi_b] = Imaginary_time_iteration_sphere( ...
        psi_a, psi_b, ...
        m_a, m_b, ...
        g_a, g_b, g_ab, ...
        N_a, N_b, ...
        L_z, ...
        Mat_V_a, Mat_V_b, ...
        geom, hbar);


end
